name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        mkdir -p ~/go/src/github.com/ihciah
        ln -s "$(pwd)/../rabbit-tcp" ~/go/src/github.com/nebulabox/rabbit-tcp
        go get -v -t -d ./...

    - name: Build
      run: go build -v cmd/rabbit.go
